#!/bin/bash

#Define list of Shellys
shellys=("192.168.173.10" "192.168.173.11" "192.168.173.12" )

for i in "${shellys[@]}"; do
  has_update="$(curl http://$i/status --user admin:admin --output - -s | python3 -c "import sys, json; print(json.load(sys.stdin)['has_update'])")"
  if [ $has_update = "True" ]
   then
    echo "1 \"Shelly Firmware $i\" - has update pending."
   else
    echo "0 \"Shelly Firmware $i\" - has no update pending."
  fi
done